### ISSUE TITLE
why the filter and the categories  taken all the width of the page ?

### ISSUE THREAD

**Issue by nuwrss** [WebAhead7/E-Strore#7]
why the filter and the categories  taken all the width of the page ?

**Comment by mjmajadly** [comment]
No time to finish all the css stuff 😪

**Comment by mjmajadly** [comment]
![ttttt](https://user-images.githubusercontent.com/43019810/100354408-d2cd5900-2ff8-11eb-87b8-efc7d227ce21.PNG)
